application:
  version: 1.0.0.RELEASE
  formatted-version: (v1.0.0.RELEASE)
server:
  port: 8002
spring:
  application:
    name: spring-cloud-config-client
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        hostname:  192.168.0.177
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 15s
        tags: ${spring.application.name}
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info