server:
  port: 1001
spring:
  application:
    name: consul-client-1
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        hostname:  192.168.0.177
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 15s
        tags: ${spring.application.name}
# 健康监控
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
consul:
  address: ${spring.cloud.consul.host}:${spring.cloud.consul.port}
