application:
  version: 1.0.0.RELEASE
  formatted-version: (v1.0.0.RELEASE)
server:
  port: 2001
spring:
  application:
    name: spirng-boot-rabbitmq
  rabbitmq:
    host: 47.106.108.22
    password:
    port: 5672
    username: admin

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info