application:
  version: 1.0.0.RELEASE
  formatted-version: (v1.0.0.RELEASE)
server:
  port: 8001
spring:
  application:
    name: spring-cloud-config
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        hostname:  192.168.0.177
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 15s
        tags: ${spring.application.name}
    config:
      server:
        git:
          uri: https://gitee.com/aikaiqiang/config-repo-dev.git
      label: master

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info